{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nAllureTestReports.py:11: AssertionError"}, "description": "this test fails", "start": 1580204610274, "stop": 1580204610275, "uuid": "afc7236d-0f17-4d36-ad89-c65ce07d0703", "historyId": "170c955c93af35c300451e8e938abf6b", "testCaseId": "f8cc61bce86fd266bb81839d456c4767", "fullName": "AllureTestReports#test_failure", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "16720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}