{"name": "test_xfail_expected_failure", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\nAllureTestReports.py:26: AssertionError"}, "description": "this test is an xfail that will be marked as expected failure", "start": 1580197504880, "stop": 1580197504880, "uuid": "48819f37-b37d-43b4-bce7-705c0428a7ce", "historyId": "0ad0cdf8b680be19df870377629b9af8", "testCaseId": "aeabe0ef4f21ab4c6e4c3757157979e5", "fullName": "AllureTestReports#test_xfail_expected_failure", "labels": [{"name": "suite", "value": "AllureTestReports"}, {"name": "host", "value": "USBLRNPAVANKUM1"}, {"name": "thread", "value": "32012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AllureTestReports"}]}